[workspace]
members = ["generator", "openai-types"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.95"
heck = "0.5.0"
quote = "1.0.40"
serde = "1.0.217"
serde_json = "1.0.140"
serde_yaml = "0.9.33"
syn = "2.0.101"
