[package]
name = "openai-openapi-generator-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
quote.workspace = true
syn = { workspace = true, features = ["extra-traits", "full", "visit-mut"] }

[lib]
proc-macro = true
