name: cargo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo clippy --all-features --all-targets --locked -- --deny=warnings
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo test --locked

  openai-openapi-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -LO https://app.stainless.com/api/spec/documented/openai/openapi.documented.yml
      - run: rustup update
      - run: >-
          cargo run --bin=openai-openapi-generator --locked --
          --document=openapi.documented.yml
          --types=openai-openapi-types/src/generated.rs
          --functions=openai-openapi-http/src/generated.rs
      - run: cargo fmt
      - run: git diff --exit-code
